-- -*- lua -*-
whatis([[Name : intel/15.0.3]])
whatis([[Version : 1.1]])
help([[The intel 2015 compiler.]])

-- This is the one users should load to get intel's toolchain
add_property("state", "ignore")

-- MODULEPATH modifications
prepend_path("MODULEPATH", "/share/apps/spack/spack_all/share/spack/lmod/linux-rhel6-x86_64/intel/15.0.3/")
-- This one is a spackism
prepend_path("MODULEPATH", "/share/apps/spack/spack_all/share/spack/lmod/linux-rhel6-x86_64/intel-parallel-studio/composer.2015.3-7gite2v/intel/15.0.3")

-- The psxe/2015 module is what was generated by actually installing
-- the intel toolchain, and defines the most important variables
always_load("psxe/2015")

-- set compiler defaults
setenv("CC",    "icc")
setenv("CXX",  "icpc")
setenv("FC",  "ifort")
setenv("F77", "ifort")
